package SquareStats::App::Model::SS;

use strict;
use base 'Catalyst::Model::DBIC::Schema';

__PACKAGE__->config(
    schema_class => 'SquareStats::Schema',
    
    connect_info => {
        dsn => 'dbi:Pg:dbname=squarestats',
        user => '',
        password => '',
    }
);

=head1 NAME

SquareStats::App::Model::SS - Catalyst DBIC Schema Model

=head1 SYNOPSIS

See L<SquareStats::App>

=head1 DESCRIPTION

L<Catalyst::Model::DBIC::Schema> Model using schema L<SquareStats::Schema>

=head1 GENERATED BY

Catalyst::Helper::Model::DBIC::Schema - 0.65

=head1 AUTHOR

Rikki Guy

=head1 LICENSE

This library is free software, you can redistribute it and/or modify
it under the same terms as Perl itself.

=cut

1;
